imports:
    - { resource: ../../conf/parameters.yml }
#    - { resource: ../../vendor/teon/symfony/app/config/config-defaults.yml }
#    - { resource: ../../vendor/teon/symfony/app/config/defaults-doctrine.yml }
#    - { resource: ../../vendor/teon/symfony/app/config/defaults-frontend-bootstrap.yml }
    - { resource: ../../vendor-dev/teon-symfony/app/config/defaults-common.yml }
    - { resource: ../../vendor-dev/teon-symfony/app/config/defaults-doctrine.yml }
    - { resource: ../../vendor-dev/teon-symfony/app/config/defaults-frontend-bootstrap.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    assets:
        packages:
            documlean:
                base_path: /assets/documlean/
            documlean_css:
                base_path: /assets/documlean/css/
            documlean_js:
                base_path: /assets/documlean/js/

            documlean_img:
                base_path: /assets/documlean/img/



doctrine_migrations:
    namespace: Documlean\Db\Migrations

avanzu_doctrine_prefix:
    prefix: %database_table_prefix%



### Entity tagging
#
fpn_tag:
    model:
        tag_class:     Documlean\Entity\Tag
        tagging_class: Documlean\Entity\Tagging
